#!/bin/bash

### BEGIN INIT INFO
# Provides:           dnsflow
# Required-Start:     $syslog $remote_fs
# Required-Stop:      $syslog $remote_fs
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  DeepField DNS telemetry tool.
### END INIT INFO

BASE=$(basename $0)

# modify these in /etc/default/$BASE (/etc/default/dnsflow)
DNSFLOW=/usr/local/sbin/$BASE
DNSFLOW_PIDFILE=/var/run/$BASE.pid
DNSFLOW_OPTS=
DNSFLOW_DESC="DNSFlow"

# Get lsb functions
. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
	. /etc/default/$BASE
fi

# see also init_is_upstart in /lib/lsb/init-functions (which isn't available in Ubuntu 12.04, or we'd use it)
if [[ -x /sbin/initctl ]] && [[ ! $(/sbin/initctl version 2> /dev/null) =~ "upstart" ]] ; then
	log_failure_msg "$DNSFLOW_DESC is managed via upstart, try using service $BASE $1"
	exit 1
fi

# Check dnsflow is present
if [ ! -x $DNSFLOW ]; then
	log_failure_msg "$DNSFLOW not present or not executable"
	exit 1
fi

fail_unless_root() {
	if [ "$(id -u)" != '0' ]; then
		log_failure_msg "$DNSFLOW_DESC must be run as root"
		exit 1
	fi
}

case "$1" in
	start)
		fail_unless_root

		log_begin_msg "Starting $DNSFLOW_DESC: $BASE"
		start-stop-daemon \
            --start \
            --background \
			--exec "$DNSFLOW" \
			--pidfile "$DNSFLOW_PIDFILE" \
			-- \
				-P "$DNSFLOW_PIDFILE" \
				$DNSFLOW_OPTS
		log_end_msg $?
		;;

	stop)
		fail_unless_root
		log_begin_msg "Stopping $DNSFLOW_DESC: $BASE"
		start-stop-daemon --stop --pidfile "$DNSFLOW_PIDFILE"
		log_end_msg $?
		;;

	restart)
		fail_unless_root
		dnsflow_pid=`cat "$DNSFLOW_PIDFILE" 2>/dev/null`
		[ -n "$dnsflow_pid" ] \
			&& ps -p $dnsflow_pid > /dev/null 2>&1 \
			&& $0 stop
		$0 start
		;;

	force-reload)
		fail_unless_root
		$0 restart
		;;

	status)
		status_of_proc -p "$DNSFLOW_PIDFILE" "$DNSFLOW" dnsflow
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

exit 0
